name: Bug report
description: Report a problem with KubeSnooze
title: "bug: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Clear, concise description.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs or error output.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version/tag are you using?
      placeholder: v0.1.0
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Kubernetes version, distro, and any relevant context.
      placeholder: |
        Kubernetes: 1.29
        Distro: EKS/GKE/AKS/kind/etc
        OS: ...
