name: Feature request
description: Suggest an idea or improvement
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see?
      placeholder: Clear, concise description.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this valuable? What problem does it solve?
      placeholder: Describe the use case.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should it work?
      placeholder: Outline an approach or behavior.
