//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

/*
Copyright 2026.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnoozeBehavior) DeepCopyInto(out *SnoozeBehavior) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.HPAMinReplicas != nil {
		in, out := &in.HPAMinReplicas, &out.HPAMinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.SuspendCronJobs != nil {
		in, out := &in.SuspendCronJobs, &out.SuspendCronJobs
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnoozeBehavior.
func (in *SnoozeBehavior) DeepCopy() *SnoozeBehavior {
	if in == nil {
		return nil
	}
	out := new(SnoozeBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeSnoozeSpec) DeepCopyInto(out *KubeSnoozeSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Sleep.DeepCopyInto(&out.Sleep)
	in.Wake.DeepCopyInto(&out.Wake)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeSnoozeSpec.
func (in *KubeSnoozeSpec) DeepCopy() *KubeSnoozeSpec {
	if in == nil {
		return nil
	}
	out := new(KubeSnoozeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeSnoozeStatus) DeepCopyInto(out *KubeSnoozeStatus) {
	*out = *in
	if in.LastSleepTime != nil {
		in, out := &in.LastSleepTime, &out.LastSleepTime
		*out = (*in).DeepCopy()
	}
	if in.LastWakeTime != nil {
		in, out := &in.LastWakeTime, &out.LastWakeTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeSnoozeStatus.
func (in *KubeSnoozeStatus) DeepCopy() *KubeSnoozeStatus {
	if in == nil {
		return nil
	}
	out := new(KubeSnoozeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeSnooze) DeepCopyInto(out *KubeSnooze) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeSnooze.
func (in *KubeSnooze) DeepCopy() *KubeSnooze {
	if in == nil {
		return nil
	}
	out := new(KubeSnooze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeSnooze) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeSnoozeList) DeepCopyInto(out *KubeSnoozeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeSnooze, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeSnoozeList.
func (in *KubeSnoozeList) DeepCopy() *KubeSnoozeList {
	if in == nil {
		return nil
	}
	out := new(KubeSnoozeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeSnoozeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
